In [28]:
import pandas as pd
import numpy as np

df = pd.read_csv("Retail Sales Dataset.csv")

df.head()

,Order ID,Date,Customer ID,Gender,Age,Product Category,Payment Method,City,Store Type,Quantity,Price per Unit,Total Amount,Total Price,Delivery Status,High Value Order,Sales Rep E-mail
0,559,01/01/2023,CUST559,Female,40,Clothing,Credit Card,Miami,Department Store,4,300,1200,1200,Pending,Yes,miamirep@gmail.com
1,180,01/01/2023,CUST180,Male,41,Clothing,Debit Card,San Francisco,Pharmacy,3,300,900,900,Pending,Yes,sanfranciscorep@gmail.com
2,522,01/01/2023,CUST522,Male,46,Beauty,Debit Card,San Francisco,Specialty Store,3,500,1500,1500,Completed,Yes,sanfranciscorep@gmail.com
3,979,02/01/2023,CUST979,Female,19,Beauty,Mobile Payment,Boston,Convenience Store,1,25,25,25,Completed,No,bostonrep@gmail.com
4,163,02/01/2023,CUST163,Female,64,Clothing,Mobile Payment,Chicago,Pharmacy,3,50,150,150,Pending,No,chicagorep@gmail.com

In [29]:
df.shape

(1000, 16)

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order ID           1000 non-null   int64
 1   Date               1000 non-null   str
 2   Customer ID        1000 non-null   str
 3   Gender             1000 non-null   str
 4   Age                1000 non-null   int64
 5   Product Category   1000 non-null   str
 6   Payment Method     1000 non-null   str
 7   City               1000 non-null   str
 8   Store Type         1000 non-null   str
 9   Quantity           1000 non-null   int64
 10  Price per Unit     1000 non-null   int64
 11  Total Amount       1000 non-null   int64
 12  Total Price        1000 non-null   int64
 13  Delivery Status    1000 non-null   str
 14  High Value Order   1000 non-null   str
 15  Sales Rep E-mail   1000 non-null   str
dtypes: int64(6), str(10)
memory usage: 125.1 KB

In [31]:
print("Missing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

Missing values:
Order ID             0
Date                 0
Customer ID          0
Gender               0
Age                  0
Product Category     0
Payment Method       0
City                 0
Store Type           0
Quantity             0
Price per Unit       0
Total Amount         0
Total Price          0
Delivery Status      0
High Value Order     0
Sales Rep E-mail     0
dtype: int64

Duplicate rows:
0

In [32]:
df.describe()

,Order ID,Age,Quantity,Price per Unit,Total Amount,Total Price
count,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,41.39200,2.632000,179.890000,476.160000,476.160000
std,288.819436,13.68143,1.465853,189.681356,620.188349,620.188349
min,1.000000,18.00000,1.000000,25.000000,25.000000,25.000000
25%,250.750000,29.00000,1.000000,30.000000,60.000000,60.000000
50%,500.500000,42.00000,3.000000,50.000000,150.000000,150.000000
75%,750.250000,53.00000,4.000000,300.000000,900.000000,900.000000
max,1000.000000,64.00000,10.000000,500.000000,5000.000000,5000.000000

In [33]:
numeric_cols = ["Age","Quantity","Price per Unit","Total Amount","Total Price"]

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(col, "-> Outliers:", len(outliers))

Age -> Outliers: 0
Quantity -> Outliers: 14
Price per Unit -> Outliers: 0
Total Amount -> Outliers: 8
Total Price -> Outliers: 8

In [34]:
Q1  = df["Quantity"].quantile(0.25)
Q3 = df["Quantity"].quantile(0.75)
IQR = Q3 - Q1

upper = Q3 + 1.5 * IQR

print("Q1:",Q1)
print("Q3:",Q3)
print("IQR",IQR)
print("Upper limit", upper)

outliers = df[df["Quantity"] > upper]

print("Number of Quantity outliers:", len(outliers))

Q1: 1.0
Q3: 4.0
IQR 3.0
Upper limit 8.5
Number of Quantity outliers: 14

In [35]:
outliers = df[df["Quantity"] > upper]

outliers[["Order ID", "Quantity", "Price per Unit", "Total Amount"]]

     Order ID  Quantity  Price per Unit  Total Amount
38         15        10             500          5000
41         14        10              30           300
139         8        10              25           250
174       910         9              50           450
207        38        10              50           500
245       891         9             300          2700
252       886         9             300          2700
264        23        10              30           300
290        17        10              25           250
401        31        10             300          3000
755        10        10              50           500
771       872         9              25           225
811       869         9             500          4500
833       898         9              30           270

In [36]:
outliers[["Order ID", "Quantity", "Price per Unit", "Total Amount", "Total Price"]]

     Order ID  Quantity  Price per Unit  Total Amount  Total Price
38         15        10             500          5000         5000
41         14        10              30           300          300
139         8        10              25           250          250
174       910         9              50           450          450
207        38        10              50           500          500
245       891         9             300          2700         2700
252       886         9             300          2700         2700
264        23        10              30           300          300
290        17        10              25           250          250
401        31        10             300          3000         3000
755        10        10              50           500          500
771       872         9              25           225          225
811       869         9             500          4500         4500
833       898         9              30           270          270

In [37]:
df["Calculated Amount"] = df["Quantity"] * df["Price per Unit"]

df[df["Calculated Amount"] != df["Total Amount"]][
    ["Order ID", "Quantity", "Price per Unit", "Total Amount", "Calculated Amount"]
]

Empty DataFrame
Columns: [Order ID, Quantity, Price per Unit, Total Amount, Calculated Amount]
Index: []

In [38]:
df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)

In [39]:
df["Date"].dtype

dtype('<M8[us]')

In [40]:
summary = pd.DataFrame({
    "Metric": ["Rows", "Columns", "Missing Values", "Duplicate Rows"],
    "Before": [1000, 16, 0, 0],
    "After": [df.shape[0], df.shape[1], df.isnull().sum().sum(), df.duplicated().sum()]
})

summary

           Metric  Before  After
0            Rows    1000   1000
1         Columns      16     17
2  Missing Values       0      0
3  Duplicate Rows       0      0

In [41]:
df.drop(columns=["Calculated Amount"], inplace=True)

In [42]:
df.to_csv("Retail_Sales_Cleaned.csv", index=False)

## Observation

- Dataset contains 1000 rows and 16 columns.
- No missing values were found.
- No duplicate rows were found.
- Date column was converted from string to datetime format.
- IQR method detected some outliers in Quantity and Total Amount.
- Quantity and Total Amount were checked for consistency.
- Detected outliers were retained for further analysis.
- The cleaned dataset was saved as Retail_Sales_Cleaned.csv.